runtime: python27
api_version: 1
threadsafe: true
instance_class: F1

automatic_scaling:
  max_idle_instances: 0

default_expiration: "10m"
  
libraries:
- name: jinja2
  version: latest

- name: ssl
  version: 2.7.11

handlers:
- url: /_ah/task/.*
  script: main.app
  login: admin

- url: /.*
  script: main.app
  login: admin
  
# inbound_services:
# - warmup

# includes:
# - mapreduce/include.yaml

# builtins:
# - appstats: on
#- deferred: on
# - remote_api: on

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
# - ui2/node_modules/(.*)
# - webapp/node_modules/(.*)


