runtime: python27
api_version: 1
threadsafe: true
service: api
instance_class: F2
  
automatic_scaling:
  max_idle_instances: 1
  max_pending_latency: 50ms
#  max_concurrent_requests: 4
  
default_expiration: "10m"

env_variables:
  GAE_USE_SOCKETS_HTTPLIB : 'anyvalue'
   
libraries:
- name: jinja2
  version: latest

- name: ssl
  version: 2.7.11

#runtime: python27
#api_version: 1
#threadsafe: true
#automatic_scaling:
#  max_idle_instances: 2 
#  
#libraries:
#- name: jinja2
#  version: latest
#
#- name: ssl
#  version: latest

handlers:
- url: /.*
  script: main.app
  login: admin
  
inbound_services:
#   - channel_presence
  - warmup

includes:
- mapreduce/include.yaml

builtins:
- appstats: on
#- deferred: on
- remote_api: on

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ui2/node_modules/(.*)
- webapp/node_modules/(.*)


